services:
  hiurachat:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ruriys/hiurachat:latest
    volumes:
      - ./config.yml:/root/config.yml
      - ./logs:/root/logs
