services:
  hiurachat:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ruriys/hiurachat:latest
    volumes:
      - ./configs:/root/configs
      - ./logs:/root/logs
